---
- hosts: all
  become: true
  roles:
    - role: pkorobeinikov.locale
      locale_names:
        - en_US.UTF-8
        - ru_RU.UTF-8
      locale_env_vars:
        - LC_ALL=ru_RU.UTF-8
        - LANG=ru_RU.UTF-8

    - role: pkorobeinikov.tzdata
      tzdata_timezone: America/Cancun
