---
- hosts: example-nginx
  become: true
  roles:
    - role: pkorobeinikov.apt-repository
      apt_repository_repositories:
        - repo: deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx
          key: http://nginx.org/keys/nginx_signing.key

    - role: pkorobeinikov.nginx
      nginx_package_version: 1.9.15-1~trusty
      nginx_conf_templates:
        - { src: nginx/nginx.conf.j2, dest: /etc/nginx/nginx.conf }
        - { src: nginx/conf.d/app.conf.j2, dest: /etc/nginx/conf.d/app.conf }
